// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQGekL7kBNa4qVaTnwo9I5bi4krnwXghU',
    appId: '1:819842624612:web:fce65c0afd2f12b799c371',
    messagingSenderId: '819842624612',
    projectId: 'meetx-4d090',
    authDomain: 'meetx-4d090.firebaseapp.com',
    storageBucket: 'meetx-4d090.appspot.com',
    measurementId: 'G-8R6LCY192Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqHDfP119Ol5JlOuPbhuiAzmX7Zp0QDbw',
    appId: '1:819842624612:android:4ec9ce096a91196f99c371',
    messagingSenderId: '819842624612',
    projectId: 'meetx-4d090',
    storageBucket: 'meetx-4d090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlNS-QtcUYCIjN6V4U7vPT3ECN5AbVEyo',
    appId: '1:819842624612:ios:59f5aaa06c66ecb299c371',
    messagingSenderId: '819842624612',
    projectId: 'meetx-4d090',
    storageBucket: 'meetx-4d090.appspot.com',
    iosClientId: '819842624612-el78smcu0hm61g0c3m2pj1pkm1dei7u2.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlNS-QtcUYCIjN6V4U7vPT3ECN5AbVEyo',
    appId: '1:819842624612:ios:db94787ca9d4077e99c371',
    messagingSenderId: '819842624612',
    projectId: 'meetx-4d090',
    storageBucket: 'meetx-4d090.appspot.com',
    iosClientId: '819842624612-e113st3q2s6nth574cv0latr7b0902ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetx.RunnerTests',
  );
}
